KR-HS/SafeWaySeoul

DriverApp/src/main/resources/static/css/modal/startManage.css
DriverApp/src/main/resources/static/js/home.js
DriverApp/src/main/resources/static/js/modal/startManage.js
DriverApp/src/main/resources/templates/home.html

startManage화면 모달로 작동하도록 수정했습니다.

2025-04-16 startManage modal fix

---

DriverApp/src/main/resources/static/css/driver/manage.css
DriverApp/src/main/resources/templates/driver/manage.html
DriverApp/src/main/resources/templates/home.html
UserApp/src/main/resources/static/css/tracing.css
UserApp/src/main/resources/static/js/tracing.js
UserApp/src/main/resources/templates/tracing.html

tracing화면 지도구현, driverApp manage화면 지도구현

tracing화면 지도구현, driverApp manage화면 지도구현

---

UserApp/src/main/resources/templates/login/IdFind.html

유경-아이디 찾기 추가

---

UserApp/src/main/resources/static/css/mypage.css
UserApp/src/main/resources/templates/user/mypage.html

마이페이지 내 정보 세션 정보 받아 와서 해당 정보 바탕으로 화면에 띄우기
마이페이지 내 아이 리스트 정보 받아와서 띄우기
모달창 띄우기

0421 주말 개인 작업 내용

---

DriverApp/src/main/resources/application.properties
UserApp/src/main/resources/templates/home.html

driverApp의 데이터베이스 연결이 다른 DB에 연결되어 있는 현상을 수정하였습니다.

2025-04-21 dirverApp db connect fix

---

UserApp/src/main/java/com/project/userapp/config/WebConfig.java
UserApp/src/main/java/com/project/userapp/controller/MainController.java
UserApp/src/main/resources/templates/user/mypage.html

04/21 10:21 AM

---

DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/resources/mapper/DriverMapper.xml
DriverApp/src/main/resources/templates/include/baseLayout.html

driver login수정

---

DriverApp/src/main/resources/static/css/common.css
DriverApp/src/main/resources/static/js/common.js
DriverApp/src/main/resources/templates/include/baseLayout.html
DriverApp/src/main/resources/templates/include/headerbaseLayout.html

dirverApp의 Header도 userApp의 Header와 동일하게 작동하게 수정

2025-04-21 driverApp header modify

---

DriverApp/src/main/java/com/project/driverapp/command/ChildrenVO.java
DriverApp/src/main/java/com/project/driverapp/command/KinderVO.java
DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/java/com/project/driverapp/driver/mapper/DriverMapper.java
DriverApp/src/main/java/com/project/driverapp/driver/service/DriverService.java
DriverApp/src/main/java/com/project/driverapp/driver/service/DriverServiceImpl.java
DriverApp/src/main/resources/mapper/DriverMapper.xml
DriverApp/src/main/resources/static/css/driver/manage.css
DriverApp/src/main/resources/static/js/modal/startManage.js
DriverApp/src/main/resources/templates/driver/manage.html
UserApp/src/main/java/com/project/userapp/children/service/ChildrenService.java
UserApp/src/main/resources/mapper/ChildrenMapper.xml

기사manage화면에서 하차할 아이들리스트

---

DriverApp/src/main/resources/templates/driver/manage.html

기사mapSearch 기능 구현

---

DriverApp/src/main/java/com/project/driverapp/controller/LoginController.java
UserApp/src/main/java/com/project/userapp/controller/LoginController.java

로그인 할 때, 아이디 혹은 비밀번호만 입력되어도 로그인이 되는 오류 수정.
아이디 혹은 비밀번호만 입력 받고, 해당값이 db에 있으면 로그인이 되고 있던 버그 수정.

2025-04-22 login bug fix

---

DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/java/com/project/driverapp/driver/mapper/DriverMapper.java
DriverApp/src/main/java/com/project/driverapp/driver/service/DriverService.java
DriverApp/src/main/java/com/project/driverapp/driver/service/DriverServiceImpl.java
UserApp/src/main/java/com/project/userapp/controller/LoginController.java

기사의 유치원 정보를 원래는 하나 받는 형태이지만 리스트를 통해서 여러개 받게 수정.

2025-04-22 driver kinder get with list

---

UserApp/src/main/java/com/project/userapp/controller/LoginController.java
UserApp/src/main/java/com/project/userapp/kinder/service/KinderServiceImpl.java
UserApp/src/main/resources/static/css/login/pswFind.css
UserApp/src/main/resources/static/js/FindUserId.js
UserApp/src/main/resources/static/js/login/pswFind.js
UserApp/src/main/resources/templates/FindUserId.html
UserApp/src/main/resources/templates/login/login.html
UserApp/src/main/resources/templates/login/pswFind.html
UserApp/src/main/resources/templates/updatePw.html

04/22 02:37PM  손유경의 두근두근 커밋

---

UserApp/build.gradle
UserApp/src/main/java/com/project/userapp/config/WebConfig.java
UserApp/src/main/java/com/project/userapp/controller/KinderController.java
UserApp/src/main/java/com/project/userapp/controller/MainController.java
UserApp/src/main/java/com/project/userapp/entity/Kinder.java
UserApp/src/main/java/com/project/userapp/entity/Location.java
UserApp/src/main/java/com/project/userapp/kinder/service/KinderService.java
UserApp/src/main/java/com/project/userapp/kinder/service/KinderServiceImpl.java
UserApp/src/main/java/com/project/userapp/repository/KinderRepository.java
UserApp/src/main/java/com/project/userapp/util/Criteria.java
UserApp/src/main/java/com/project/userapp/util/PageDTO.java
UserApp/src/main/java/com/project/userapp/util/interceptor/FirstVisitInterceptor.java
UserApp/src/main/java/com/project/userapp/util/interceptor/LoginInterceptor.java
UserApp/src/main/resources/application.properties
UserApp/src/main/resources/static/css/home.css
UserApp/src/main/resources/static/js/home.js
UserApp/src/main/resources/static/js/login/join.js
UserApp/src/main/resources/templates/home.html
UserApp/src/main/resources/templates/temp_code_storage

유저 메인페이지유치원 리스트

---

UserApp/src/main/java/com/project/userapp/children/service/ChildrenServiceImpl.java
UserApp/src/main/java/com/project/userapp/file/service/FileService.java
UserApp/src/main/java/com/project/userapp/file/service/FileServiceImpl.java
UserApp/src/main/java/com/project/userapp/files/mapper/FilesMapper.java
UserApp/src/main/java/com/project/userapp/files/service/FilesService.java
UserApp/src/main/java/com/project/userapp/files/service/FilesServiceImpl.java
UserApp/src/main/java/com/project/userapp/kindermatch/mapper/KinderMatchMapper.java
UserApp/src/main/java/com/project/userapp/kindermatch/service/KinderMatchService.java
UserApp/src/main/java/com/project/userapp/kindermatch/service/KinderMatchServiceImpl.java
UserApp/src/main/resources/mapper/FilesMapper.xml
UserApp/src/main/resources/mapper/KinderMatchMapper.xml
UserApp/src/main/resources/static/js/myPage.js

자녀 카드 삭제 기능을 좀 더 다듬었습니다.
자녀 카드를 삭제할 경우 연관되어 있는 FILES테이블과 KINDERMATCH테이블에서도 같이 삭제되게 했고 삭제 확인 모달창도 추가해봤어요.

04/22 07:33PM Andy

---

DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/java/com/project/driverapp/drivertable.txt
DriverApp/src/main/resources/templates/driver/manage.html

기사manage창에서 화면업로드시 db에서 불러와서 출발지경유지도착지 경로찍어주기

기사manage창에서 화면업로드시 db에서 불러와서 출발지경유지도착지 경로찍어주기

---

UserApp/src/main/java/com/project/userapp/controller/LoginController.java
UserApp/src/main/java/com/project/userapp/user/service/UserServiceImpl.java
UserApp/src/main/resources/mapper/UserMapper.xml
UserApp/src/main/resources/static/css/updatePw.css
UserApp/src/main/resources/static/js/updatePw.js
UserApp/src/main/resources/templates/FindUserId.html
UserApp/src/main/resources/templates/login/pswFind.html
UserApp/src/main/resources/templates/updatePw.html

아이디 찾기 - 기능 완료 
아이디 찾기 완료 페이지 - css 변경
비밀번호 찾기 - 기능 완료
비밀번호 재설정 페이지 - css변경 및 기능 완료

2025-4-23 11:31 아이디, 비밀번호 찾기 및 재설정 완료!

---

DriverApp/src/main/java/com/project/driverapp/command/ChildrenVO.java
DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/resources/mapper/DriverMapper.xml
DriverApp/src/main/resources/templates/driver/manage.html
UserApp/src/main/java/com/project/userapp/kinder/service/KinderServiceImpl.java

기사 mange화면에서 <배차정보란>-db와 연결하여 select해오기

기사 mange화면에서 <배차정보란>-db와 연결하여 select해오기

---

UserApp/src/main/java/com/project/userapp/children/service/ChildrenServiceImpl.java
UserApp/src/main/java/com/project/userapp/config/WebConfig.java
UserApp/src/main/java/com/project/userapp/controller/ChildController.java
UserApp/src/main/resources/application.properties
UserApp/src/main/resources/mapper/FilesMapper.xml
UserApp/src/main/resources/static/css/regChild.css
UserApp/src/main/resources/static/js/modal.js
UserApp/src/main/resources/static/js/myPage.js
UserApp/src/main/resources/static/js/regChild.js
UserApp/src/main/resources/templates/modal/regChild.html
UserApp/src/main/resources/templates/user/mypage.html

UX측면에서 모달창 기능들 디테일 더했습니다.
자녀 카드 프로필 사진 업로드 및 화면에서 출력하는 기능 구현했어요.

04/23 05:34PM Andy

---

DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/resources/static/css/login/join.css
DriverApp/src/main/resources/static/js/FindUserId.js
DriverApp/src/main/resources/templates/home.html
DriverApp/src/main/resources/templates/login/join.html
UserApp/src/main/java/com/project/userapp/kinder/service/KinderServiceImpl.java

DriverApp 아이디 결과페이지 버튼이랑 회원가입 양식 바꿨어요

2025-04-23 5:50 드라이버 세부 수정

---

DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/resources/mapper/DriverMapper.xml
DriverApp/src/main/resources/templates/driver/manage.html
UserApp/src/main/java/com/project/userapp/kinder/service/KinderServiceImpl.java

아이들 승하차여부 수정

---

DriverApp/src/main/java/com/project/driverapp/controller/LoginController.java
DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/resources/static/css/driver/manage.css
DriverApp/src/main/resources/static/js/driver/manage.js
DriverApp/src/main/resources/templates/driver/manage.html

도착지경유지마커부분수정과 경로찾기토글버튼추가

---

UserApp/src/main/resources/static/css/regChild.css
UserApp/src/main/resources/static/js/regChild.js
UserApp/src/main/resources/templates/modal/regChild.html

2025-04-24 regChild modal에 어린이집 검색 추가
regChild 모달에서 어린이집을 검색 할때 자동완성으로 어린이집을 검색하고, 그것의 목록을 보여주는 기능 구현

2025-04-24 regChild modal에 어린이집 검색 추가

---

UserApp/src/main/java/com/project/userapp/children/mapper/ChildrenMapper.java
UserApp/src/main/java/com/project/userapp/children/service/ChildrenService.java
UserApp/src/main/java/com/project/userapp/children/service/ChildrenServiceImpl.java
UserApp/src/main/java/com/project/userapp/controller/ChildController.java
UserApp/src/main/resources/mapper/ChildrenMapper.xml

2025-04-24 모달을 통해서 어린이 등록 (어린이집 포함) 구현 완료
모달을 통한 자녀 등록에서도 어린이집을 적어서 넣을 수 있고, 그것이 db에도 정상적으로 등록이 됨.

2025-04-24 모달을 통해서 어린이 등록 (어린이집 포함) 구현 완료

---

UserApp/src/main/resources/static/js/modal.js

내 자녀 수정할때 저장된 데이터들이 먼저 모달에 띄우게 수정

2025-04-24 내 자녀 정보 수정 수정

---

UserApp/src/main/java/com/project/userapp/location/service/LocationServiceImpl.java
UserApp/src/main/resources/mapper/LocationMapper.xml

4.24일 6시 전체 동기화(웹소켓, 유저맵띄우기)

---

DriverApp/src/main/java/com/project/driverapp/controller/LoginController.java
DriverApp/src/main/java/com/project/driverapp/kinder/mapper/KinderMapper.java
DriverApp/src/main/java/com/project/driverapp/kinder/service/KinderService.java
DriverApp/src/main/java/com/project/driverapp/kinder/service/KinderServiceImpl.java
DriverApp/src/main/resources/mapper/KinderMapper.xml
DriverApp/src/main/resources/static/css/login/join.css
DriverApp/src/main/resources/static/js/login/join.js
DriverApp/src/main/resources/templates/login/join.html

DriverApp에서 회원가입 주소 불러오기(?) 유효성 검사(?) 기능 추가
join.js
join.css
join.html
LoginController.java
KinderMapper.java
KinderMapper.xml
KinderService.java
KinderServiceImpl.java
이렇게만 건들였어요!

2025-04-24 7:16 DriverApp 주소 검사(?) 불러오기(?)

---

UserApp/src/main/java/com/project/userapp/command/ChildrenVO.java
UserApp/src/main/java/com/project/userapp/controller/MainController.java
UserApp/src/main/java/com/project/userapp/sql
UserApp/src/main/resources/mapper/LocationMapper.xml
UserApp/src/main/resources/mapper/UserMapper.xml
UserApp/src/main/resources/templates/user/tracing.html

4.25 동기화(db record, driveinfo테이블 추가및 수정)

4.25 동기화(db record, driveinfo테이블 추가및 수정)

---

DriverApp/src/main/java/com/project/driverapp/command/DriveInfoVO.java
DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/java/com/project/driverapp/driveInfo/mapper/DriveInfoMapper.java
DriverApp/src/main/java/com/project/driverapp/driveInfo/service/DriveInfoService.java
DriverApp/src/main/java/com/project/driverapp/driveInfo/service/DriveInfoServiceImpl.java
DriverApp/src/main/resources/mapper/DriveInfo.xml
DriverApp/src/main/resources/mapper/DriverMapper.xml
DriverApp/src/main/resources/static/js/modal/startManage.js
DriverApp/src/main/resources/templates/driver/manage.html
DriverApp/src/main/resources/templates/home.html

db의 변경사항이 생긴 후 필연적으로 발생하는 오류 수정 중
driverAPP의 배차카드, 기사의 어린이집, 배차카드 상세 정보 확인 기능 수정

2025-04-25 db change bug fix

---

UserApp/src/main/java/com/project/userapp/command/ChildrenVO.java
UserApp/src/main/java/com/project/userapp/controller/ChildController.java
UserApp/src/main/java/com/project/userapp/controller/MainController.java
UserApp/src/main/java/com/project/userapp/kindermatch/mapper/KinderMatchMapper.java
UserApp/src/main/java/com/project/userapp/kindermatch/service/KinderMatchService.java
UserApp/src/main/java/com/project/userapp/kindermatch/service/KinderMatchServiceImpl.java
UserApp/src/main/resources/mapper/ChildrenMapper.xml
UserApp/src/main/resources/mapper/KinderMatchMapper.xml
UserApp/src/main/resources/static/css/regChild.css
UserApp/src/main/resources/static/css/userInfoModi.css
UserApp/src/main/resources/static/js/common.js
UserApp/src/main/resources/static/js/modal.js
UserApp/src/main/resources/static/js/regChild.js
UserApp/src/main/resources/static/js/userInfoModi.js
UserApp/src/main/resources/templates/modal/regChild.html
UserApp/src/main/resources/templates/user/mypage.html
UserApp/src/main/resources/templates/user/userInfoModi.html

04/25 12:55PM Andy

---

DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/resources/static/js/modal/startManage.js

2025-04-25 db change bug fix2

---

UserApp/src/main/resources/static/css/common.css
UserApp/src/main/resources/static/css/home.css
UserApp/src/main/resources/static/js/home.js
UserApp/src/main/resources/templates/home.html

UserApp 홈에 있는 지도 모달창 디자인 수정
폰트 수정 (폰트 크기는 수정 중 ㅠㅠ)
home.html
home.js
home.css
common.css

2025-04-25 3:15 지도 모달, 폰트 수정

---

DriverApp/src/main/java/com/project/driverapp/controller/LoginController.java
DriverApp/src/main/java/com/project/driverapp/driver/mapper/DriverMapper.java
DriverApp/src/main/java/com/project/driverapp/driver/service/DriverService.java
DriverApp/src/main/java/com/project/driverapp/driver/service/DriverServiceImpl.java
DriverApp/src/main/resources/mapper/DriverMapper.xml
DriverApp/src/main/resources/static/css/login/join.css
DriverApp/src/main/resources/templates/login/join.html
UserApp/src/main/resources/mapper/UserMapper.xml

2025-04-25 7:00 운행정보 추가

---

UserApp/src/main/java/com/project/userapp/children/service/ChildrenService.java
UserApp/src/main/java/com/project/userapp/command/ChildrenVO.java
UserApp/src/main/java/com/project/userapp/controller/MainController.java
UserApp/src/main/java/com/project/userapp/kinder/service/KinderServiceImpl.java
UserApp/src/main/java/com/project/userapp/location/mapper/LocationMapper.java
UserApp/src/main/java/com/project/userapp/location/service/LocationService.java
UserApp/src/main/java/com/project/userapp/location/service/LocationServiceImpl.java
UserApp/src/main/resources/mapper/LocationMapper.xml
UserApp/src/main/resources/templates/home.html
UserApp/src/main/resources/templates/user/tracing.html

user main화면에 운행정보(P,S,E) 변환해서 나타내기
user tracing화면에 운행정보(P,S,E) 변환해서 나타내고, 운행시작시간도 변환해서 나타냄

user main화면에 운행정보(P,S,E) 변환해서 나타내기 user tracing화면에 운행정보(P,S,E) 변환해서 나타내고, 운행시작시간도 변환해서 나타냄

---

UserApp/src/main/resources/static/css/tracing.css
UserApp/src/main/resources/static/js/tracing.js
UserApp/src/main/resources/templates/user/tracing.html

tracing animation update

---

DriverApp/src/main/resources/mapper/DriverMapper.xml
DriverApp/src/main/resources/templates/home.html

2025-04-28 현수님이 고쳐줌!

---

UserApp/src/main/resources/static/js/myPage.js
UserApp/src/main/resources/templates/user/mypage.html

child화면에서 childcard에 해당아이 선택하면 tracing으로 넘어가게

child화면에서 childcard에 해당아이 선택하면 tracing으로 넘어가게

---

UserApp/src/main/java/com/project/userapp/community/mapper/CommunityMapper.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityService.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityServiceImpl.java
UserApp/src/main/java/com/project/userapp/controller/CommunityController.java
UserApp/src/main/java/com/project/userapp/sql
UserApp/src/main/resources/application.properties
UserApp/src/main/resources/mapper/CommunityMapper.xml
UserApp/src/main/resources/static/js/community/postList.js
UserApp/src/main/resources/templates/community/postDetail.html
UserApp/src/main/resources/templates/community/postList.html

커뮤니티의 글 상세보기 데이터베이스와 연동되어서 작동되게 구현

2025-04-28 community post detail db connect

---

DriverApp/src/main/java/com/project/driverapp/controller/LoginController.java
DriverApp/src/main/java/com/project/driverapp/controller/MainController.java
DriverApp/src/main/java/com/project/driverapp/driver/service/DriverServiceImpl.java
DriverApp/src/main/resources/application.properties
UserApp/src/main/java/com/project/userapp/children/service/ChildrenServiceImpl.java
UserApp/src/main/java/com/project/userapp/controller/MainController.java
UserApp/src/main/java/com/project/userapp/util/interceptor/LoginInterceptor.java
UserApp/src/main/resources/mapper/ChildrenMapper.xml
UserApp/src/main/resources/static/js/home.js

데이터 가공 수정(시간에 따른 오전/오후 record를 childVO에 담아서 가져오기)

데이터 가공 수정(시간에 따른 오전/오후 record를 childVO에 담아서 가져오기)

---

UserApp/src/main/java/com/project/userapp/command/PostVO.java
UserApp/src/main/java/com/project/userapp/controller/CommunityController.java
UserApp/src/main/resources/mapper/CommunityMapper.xml
UserApp/src/main/resources/templates/community/postList.html
UserApp/src/main/resources/templates/home.html

DB에서 데이터 연동 되서 커뮤니티 게시판에서 리스트로 출력되게

04/29 12:08PM andy

---

DriverApp/src/main/resources/mapper/DriveInfo.xml
UserApp/src/main/java/com/project/userapp/command/CommentVO.java
UserApp/src/main/java/com/project/userapp/community/mapper/CommunityMapper.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityService.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityServiceImpl.java
UserApp/src/main/java/com/project/userapp/controller/CommunityController.java
UserApp/src/main/resources/mapper/CommunityMapper.xml
UserApp/src/main/resources/static/css/community/postDetail.css
UserApp/src/main/resources/static/js/common.js
UserApp/src/main/resources/static/js/community/postDetail.js
UserApp/src/main/resources/templates/community/postDetail.html

2025-04-29 community coment

---

UserApp/src/main/java/com/project/userapp/command/CommentVO.java
UserApp/src/main/java/com/project/userapp/command/PostVO.java
UserApp/src/main/java/com/project/userapp/community/mapper/CommunityMapper.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityService.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityServiceImpl.java
UserApp/src/main/java/com/project/userapp/controller/CommunityController.java
UserApp/src/main/resources/mapper/CommunityMapper.xml
UserApp/src/main/resources/templates/community/postDetail.html
UserApp/src/main/resources/templates/community/postList.html

커뮤니티 댓글 작성한 사람 정보 가져오기 + 현재 댓글 개수 표시 + 댓글 입력 후 지금까지 지난 시간 확인하기

2025-04-29 community comment relation develop

---

UserApp/src/main/java/com/project/userapp/community/mapper/CommunityMapper.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityService.java
UserApp/src/main/java/com/project/userapp/community/service/CommunityServiceImpl.java
UserApp/src/main/java/com/project/userapp/controller/CommunityController.java
UserApp/src/main/resources/mapper/CommunityMapper.xml
UserApp/src/main/resources/static/js/community/postDetail.js
UserApp/src/main/resources/static/js/community/postList.js

커뮤니티의 검색기능(제목)을 완성 하였습니다. 
이제 댓글 작성을 아이콘을 클릭하는 것 뿐만 아니라 엔터키로 작성할 수 있도록 수정됩니다.

2025-04-29 post search success

---

UserApp/src/main/resources/templates/community/postDetail.html

postDetail의 댓글이 postCard에 들어가지 않던 오류 수정

2025-04-30 postDetail comment fix
